### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by regdocs** [WhiteFang033/SAGE#1]
How are you? Wanna hangout on Discord sometime?

**Comment by WhiteFang033** [comment]
> How are you? Wanna hangout on Discord sometime?

Ayy that's a clever way to contact me lol. Aye I'm fine and hoping the same for you. I'll be free after a month ig so...
Let's have a chat then.
Drop a message on my dm and I'll try reply as soon as I see ,yo!

**Comment by regdocs** [comment]
I have exams too. Gonna be occupied until 15th June but let's chat when you free. I'm not that active on Discord either. Nice of you to reach out here haha. It's been a while. Take care and I'll see you soon.
